### ISSUE TITLE
tendermint拜占庭共识算法.md这一章可以出个源码导读吗

### ISSUE THREAD

**Issue by malefooo** [wupeaking/tendermint_code_analysis#3]
想看看源码在哪,或者作者给个路径指引吧,感谢

**Comment by wupeaking** [comment]
不好意思， 最近在写一个pbft的具体实现 https://github.com/wupeaking/pbft_impl 暂时没有精力出源码分析的文章啦。

**Comment by malefooo** [comment]
> 不好意思，最近在写一个pbft的具体实现[https://github.comwupeaking/pbft_impl](https://github.com/wupeaking/pbft_impl)暂时没有精力出源码分析的文章啦。

好的好的,不过其他也给了我很多的帮助,感谢
